const router = require("express").Router();
const saveBrand = require("./brand")
const getBrand = require("./brandGet")
const getUsers = require("./getUsers")
const updateMission = require("./update/updateMission");
const  updateVision = require("./update/updateVision");
const updateMani = require("./update/updateMani")
const updateValues = require("./update/updateValues")
const saveComp = require("./save/saveComp")
const saveGraph = require("./save/saveGraph")
const brandColors = require ("./save/brandColors")
const uploadImage = require ("./save/uploadImage")
const updateImages = require ("./update/updateImages")
const uploadLogo = require ("./save/uploadLogo")
const deleteLogo = require ("./update/deleteLogo")
const updateVoice = require ("./update/updateVoice")
const updateMessaging = require ("./update/updateMessaging")
const updateTaglines = require ("./update/updateTaglines")
const updateFonts = require ("./update/updateFonts")
const updateCompName = require ("./update/updateCompName")
const updateSWOT = require("./update/updateCompSWOT")
const updateCompSite = require("./update/updateCompSite")
const updateCompMsg = require("./update/updateCompMsg")
const updateCompArch = require("./update/updateCompArch")
const updateCompLogos = require("./update/uploadCompLogo")
const updateCompBA = require("./update/uploadCompBA")
const saveAud = require("./save/saveAud");
const updateJTB = require("./update/updateJTB")
const updatePains = require("./update/updatePains")
const updateGains = require("./update/updateGains")
const updateInsights = require("./update/updateInsight")
const updateDemographics = require("./update/updateDemographics")
const updatePsychograhics = require("./update/updatePsychograhics")
const updateAudArchs = require("./update/updateAudArchs")
const updateAudMedia = require("./update/updateAudMedia")
const updateAudHabits = require("./update/updateAudHabits")
const updateAudSocial = require("./update/updateAudSocial")
const updatesubStrats = require("./update/updateSubStrats")
const updateAwareness = require("./update/updateAwareness")
const updateInterests = require("./update/updateInterests")
const updateDesires = require("./update/updateDesires")
const updateAction = require("./update/updateActions")
const updateDigital=require("./update/updateDigital")
const updateInPerson = require("./update/updateInPerson")
const updatePrint = require("./update/updatePrints")
const updateOther = require("./update/updateOther")
const styleTiles = require("./save/tileStyles")
const styleGuide = require("./save/uploadSG")
const readAccess = require("./access/readAccess")
const rwAccess = require("./access/rwAccess")
const regUser = require("./access/registerUser")

router.use("/brand", saveBrand);
router.use("/brands", getBrand);
router.use("/users", getUsers);
router.use("/updatemission", updateMission);
router.use("/updatevision", updateVision);
router.use("/updatemani", updateMani)
router.use("/updatevalues", updateValues)
router.use("/comp", saveComp)
router.use("/graph", saveGraph)
router.use("/brandcolors", brandColors)
router.use("/upload", uploadImage )
router.use("/updatedimages", updateImages)
router.use("/uploadlogo", uploadLogo )
router.use("/deletelogo", deleteLogo )
router.use("/updatevoice", updateVoice)
router.use("/updatemessaging", updateMessaging)
router.use("/updatetaglines", updateTaglines)
router.use("/updateFonts", updateFonts)
router.use("/updateCompName", updateCompName)
router.use("/updateSWOT", updateSWOT)
router.use("/updateCompSite", updateCompSite)
router.use("/updateCompMsg", updateCompMsg)
router.use("/updateCompArch", updateCompArch)
router.use("/uploadCompLogos", updateCompLogos)
router.use("/uploadCompBA", updateCompBA)
router.use("/aud", saveAud)
router.use("/jtbUpdate", updateJTB)
router.use("/painsUpdate", updatePains)
router.use("/gainsUpdate", updateGains)
router.use("/insightsUpdate", updateInsights)
router.use("/demographicsUpdate", updateDemographics)
router.use("/psychographicsUpdate", updatePsychograhics)
router.use("/audArchsUpdate", updateAudArchs)
router.use("/audMediaUpdate", updateAudMedia)
router.use("/audHabitsUpdate", updateAudHabits)
router.use("/audSocialUpdate", updateAudSocial)
router.use("/updatesubStrats", updatesubStrats)
router.use("/updateAwareness", updateAwareness)
router.use("/updateInterest", updateInterests)
router.use("/updateDesire", updateDesires)
router.use("/updateAction", updateAction)
router.use("/updateDigital", updateDigital)
router.use("/updatePerson", updateInPerson)
router.use("/updatePrint", updatePrint)
router.use("/updateOther", updateOther)
router.use("/styleTiles", styleTiles)
router.use("/uploadSG", styleGuide)
router.use("/readAccess", readAccess)
router.use("/rwAccess", rwAccess)
router.use("/regUser", regUser)


module.exports = router;